service: serverless-ssr-react-sc

provider:
  name: aws
  runtime: nodejs8.10
  stage: /
  region: ap-northeast-2

functions:
  lambda:
    handler: dist/lambda.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'